### ISSUE TITLE
[12.0] mrp_subcontracting

### ISSUE THREAD

**Issue by MarcoCalcagni** [OCA/manufacture#508] opened 2020-07-07 12:49 UTC
Hi, 

if a row material is used in 2 subcontracting bom with 2 different vendor.  in product on hand is not possible to determine how much and where is the product in stock. 
es 
send to subcontractor Mario  100 qty of product raw materials “A”   
send to subcontractor Bross  10 qty of product raw materials “A”   

in stock i can see in hand 110 but is missing where .

Marco

**Comment by pedrobaeza** [comment] 2020-07-07 12:53
I don't get the problem. Stock must be in suncontractor locations.

**Comment by MarcoCalcagni** [comment] 2020-07-07 13:08
ok but how I understand in which subcontractor is the row material ? 
If I have to do an Inventory Adjustments on subcontractor Mario how can i do it?

**Comment by pedrobaeza** [comment] 2020-07-07 13:10
As said, each one has a subcontractor location, so put different locations and control it that way.

This is not a bug and it's out of scope of the module, but general knowledge of Odoo, so closing.

**Closed as completed by pedrobaeza** 2020-07-07 13:10 UTC

**Comment by MarcoCalcagni** [comment] 2020-07-07 13:23
Sorry Pedro, the only way that I see is to create a specific operation type for any subcontractor and change on picking before validate . 
Is that correct? if yes is not so smart.

**Comment by pedrobaeza** [comment] 2020-07-07 14:35
No, at partner level you have the subcontractor location as is taken automatically.
