### ISSUE TITLE
8.0 [BUG] MRP Total Real Cost

### ISSUE THREAD

**Issue by JMODaERP** [OCA/manufacture#81] opened 2016-01-24 13:14 UTC
The costs charged (direct) in an order of production standard, whatever the industry sector, are calculated based on the cost of raw materials and auxiliary materials, plus the cost of operators, plus the cost of machinery. Also many companies include preparing machines (CAM,CAD,setting dies, tooling etc ) and often include cleaning the room or production facility , like pre and post tasks.

Currently, the calculations performed Odoo OCA , the costs of operators that are being 33% of the total real costs, and allocation of hours which are ignored have created the " Operators time" tab and the employee has been included HR Settings and product_id of hr_employee . 

Maybe it's an oversight (BUG) or a special way to calculate the total real costs.

If you see fit to do this repair VS improving the resolution love me , otherwise I would open a debate on the subject.

Thank you.

For example : In a production

Current Behavior.

![1 2016-01-24 12_34_48-2016-01-24 12_06_18-costs revenues - odoo-operarios 1-ingles](https://cloud.githubusercontent.com/assets/15608043/12536403/45811b70-c2a4-11e5-803b-da1a8e412a5b.jpg)

```
                                                            Visual 1
```

![2 2016-01-24 12_07_39-costs revenues - odoo-operarios 2](https://cloud.githubusercontent.com/assets/15608043/12536405/5e4b2998-c2a4-11e5-950a-6a89f924d33d.jpg)

```
                                                            Visual 2
```

![3 2016-01-24 12_08_06-costs revenues - odoo-operarios 3](https://cloud.githubusercontent.com/assets/15608043/12536408/764b6ecc-c2a4-11e5-9a92-ab9a54ea0b8c.jpg)

```
                                                             Visual 3
```

![4 2016-01-24 12_52_54-2016-01-24 12_09_02-manufacturing orders - odoo-mo-total real cost](https://cloud.githubusercontent.com/assets/15608043/12536415/9a4ceb16-c2a4-11e5-9c03-e2ba6e73a337.jpg)

```
                                                              Visual 4
```

Expectde Behavior.

![5 2016-01-24 14_04_43-sin titulo - paint](https://cloud.githubusercontent.com/assets/15608043/12536420/c05353e0-c2a4-11e5-9ffe-31ec50fec3e7.jpg)

```
                                                               Visual 5
```

**Comment by pedrobaeza** [comment] 2016-01-24 13:17
Please follow expected schema for reporting bugs:

module: mrp_production_real_cost
version: 8.0

**Steps to reproduce**
- ...

**Current behavior**

**Expected behavior**

**Comment by JMODaERP** [comment] 2016-01-24 15:09
O.K.

**Comment by JMODaERP** [comment] 2016-01-24 15:23
The actual total cost that determines the order is 1,7618.31 , which is none other than the difference between 2,264.38 and 496.07 . As I wanted to show .

```
                                                1,7618.31 = 2,264.38 - 496.07
```

![2016-01-24 13_05_49-2016-01-24 12_09_02-manufacturing orders - odoo-mo-total real cost-new](https://cloud.githubusercontent.com/assets/15608043/12537065/911cfca4-c2b6-11e5-9668-96957e652901.jpg)

Thanks Peter.

**Comment by JMODaERP** [comment] 2016-01-25 14:47
Thanks ddico, good job. O.K.

**Comment by rafaelbn** [comment] 2016-01-25 18:28
We can close this issue because https://github.com/OCA/manufacture/pull/85

**Closed as completed** 2016-01-26 20:19 UTC
